from pathlib import Path
import json
root=Path(__file__).resolve().parent
cmhc='https://www.cmhc-schl.gc.ca/professionals/housing-markets-data-and-research/market-reports/rental-market-reports-major-centres'
ca=[['BC','Vancouver',2696,'new-tenant'],['AB','Edmonton',1600,'new-tenant'],['AB','Calgary',1836,'new-tenant'],['ON','Toronto',2547,'new-tenant'],['ON','Ottawa',2155,'new-tenant'],['QC','Montréal',1644,'new-tenant'],['NS','Halifax',2058,'new-tenant'],['BC','Victoria',2120,'all-units'],['SK','Regina',1473,'all-units'],['SK','Saskatoon',1548,'all-units'],['MB','Winnipeg',1571,'all-units'],['ON','Hamilton',1656,'all-units'],['ON','Kitchener–Cambridge–Waterloo',1832,'all-units'],['ON','London',1651,'all-units'],['ON','Windsor',1454,'all-units'],['QC','Gatineau',1460,'all-units'],['QC','Quebec City',1277,'all-units']]
taxes={
'Arizona':{'rate':.025,'deduction':15750,'local':False,'source':'https://azdor.gov/sites/default/files/2023-03/BROCHURE_freetaxprep_guide.pdf','note':'2025 standard deduction; no additional charity deduction or credits.'},
'Illinois':{'rate':.0495,'deduction':2850,'exemptionCutoff':250000,'local':False,'source':'https://tax.illinois.gov/forms/incometax/currentyear/individual/il-1040-instr/what-is-new.html','note':'Personal exemption is lost in full above $250,000 federal AGI for a single filer.'},
'North Carolina':{'rate':.0425,'deduction':12750,'local':False,'source':'https://www.ncdor.gov/2025-d-401-individual-income-tax-instructions/open','note':'2025 flat rate and single-filer standard deduction.'},
'Virginia':{'brackets':[[0,.02],[3000,.03],[5000,.05],[17000,.0575]],'deduction':9680,'local':False,'source':'https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2025-760-instructions.pdf','note':'$8,750 standard deduction plus $930 personal exemption. Low-income relief omitted.'},
'Louisiana':{'rate':.03,'deduction':12500,'local':False,'source':'https://dam.ldr.la.gov/lawspolicies/RIB-25-012-Louisiana-Individual-Income-Tax-Reform-1.pdf','note':'2025 flat rate; no separate federal-income-tax deduction.'},
'Michigan':{'rate':.0425,'deduction':5800,'local':True,'source':'https://www.michigan.gov/taxes/iit/tax-guidance/tax-year-info/tax-year-2025-guidance','note':'Municipal income taxes require an entered annual total; state rate includes one personal exemption.'},
'Kentucky':{'rate':.04,'deduction':3270,'local':True,'source':'https://revenue.ky.gov/News/pages/kentucky-dor-announces-2025-standard-deduction.aspx','note':'County/city occupational taxes require an entered total; low-income family-size credit omitted.'},
'Colorado':{'rate':.044,'deduction':15750,'deductionCutoff':300000,'highIncomeDeduction':12000,'payrollRate':.0045,'payrollCap':176100,'local':True,'source':'https://tax.colorado.gov/individual-income-tax-guide','note':'Deduction limited to $12,000 above $300,000 AGI. Employee state-plan FAMLI included; local occupational taxes need an entered total. No optional self-employed FAMLI premium or TABOR refund.'}}
sources=[['HUD FY2025 rent schedule · studio through four bedrooms','https://www.huduser.gov/portal/datasets/fmr/fmr2025/FY2025_FMR_Schedule.pdf'],['HUD April 28, 2025 rent revisions','https://www.federalregister.gov/documents/2025/03/28/2025-05345/fair-market-rents-for-the-housing-choice-voucher-program-moderate-rehabilitation-single-room'],['HUD rent definition and included utilities','https://www.huduser.gov/portal/sites/default/files/pdf/fmr-overviewFY25.pdf'],['CMHC 2025 city rents and new-tenant comparison',cmhc],['AAMC Class of 2025 debt fact card','https://store.aamc.org/downloadable/download/sample/sample_id/652/']]
sources += [[state+' · official 2025 tax reference',v['source']] for state,v in taxes.items()]
sources += [['Illinois exemption income limits','https://tax.illinois.gov/forms/incometax/currentyear/individual/il-1040-instr/step-4---exemptions.html'],['Virginia standard deduction','https://www.tax.virginia.gov/news/new-virginia-tax-laws-july-1-2025'],['Virginia personal exemption','https://www.tax.virginia.gov/exemptions'],['Virginia tax rate schedule','https://www.tax.virginia.gov/sites/default/files/2016-12/TAXTABLE.pdf'],['Arizona flat tax rate','https://azdor.gov/forms/individual'],['Kentucky income tax rate','https://revenue.ky.gov/Individual/Individual-Income-Tax/Pages/default.aspx'],['Michigan cities with income taxes','https://www.michigan.gov/taxes/questions/iit/accordion/general/what-cities-impose-an-income-tax'],['Kentucky local occupational tax example','https://www.lexingtonky.gov/working/business-licensing-taxes/occupational-license-fee-rates-current-forms'],['Colorado FAMLI 2025 wage cap · CDLE','https://content.govdelivery.com/accounts/CODLE/bulletins/3c9e0c5'],['Colorado FAMLI 2025 premium bulletin · CDLE','https://content.govdelivery.com/accounts/CODLE/bulletins/3cf1c65']]
sources += [['FCAC mortgage renewal and interest','https://www.canada.ca/en/financial-consumer-agency/services/mortgages/interest-on-mortgages.html'],['Canadian mortgage compounding convention · Scotiabank calculator','https://www.scotiabank.com/ca/en/personal/mortgages/mortgage-calculator.html']]
sources += [['Bank of Canada · 2025 annual average exchange rates','https://www.bankofcanada.ca/rates/exchange/annual-average-exchange-rates/']]
obj={'fxCADperUSD':1.3978,'reviewed':'2026-09-09','housingUS':json.loads((root/'housing-us.json').read_text()),'housingCA':ca,'taxes':taxes,'debtMedian':215000,'sources':sources}
(root.parent/'dist/layers-data.js').write_text('/* Frozen source data; see Sources in the app and research notes. */\nglobalThis.LAYERS_DATA='+json.dumps(obj,ensure_ascii=False,separators=(',',':'))+';\n')
print('layers data:',len(obj['housingUS']),'U.S. records;',len(ca),'Canadian cities;',len(taxes),'new states')
